development:
  adapter: postgresql
  encoding: unicode
  database: barterville_development  #name is name of app _development 
  pool: 5
  host: localhost
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: barterville_production  #name is name of app _development 
  pool: 5
  host: localhost
  username: postgres
  password:
